-- ==========================================
-- 1. TẠO CÁC BẢNG ĐỘC LẬP (Không có khóa ngoại)
-- ==========================================

-- Bảng KHOA
CREATE TABLE KHOA (
    MAKHOA VARCHAR2(20) PRIMARY KEY,
    TENKHOA NVARCHAR2(100)
);

-- Bảng NHÂN VIÊN
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN NVARCHAR2(100),
    PHAI NVARCHAR2(10),
    NGAYSINH DATE,
    CMND VARCHAR2(20),
    QUEQUAN NVARCHAR2(200),
    SODT VARCHAR2(15),
    VAITRO NVARCHAR2(50),
    CHUYENKHOA NVARCHAR2(100),
    COSO NVARCHAR2(50) -- Bổ sung cho OLS (HCM, HN, HP)
);

-- Bảng BỆNH NHÂN
CREATE TABLE BENHNHAN (
    MABN VARCHAR2(20) PRIMARY KEY,
    TENBN NVARCHAR2(100),
    PHAI NVARCHAR2(10),
    NGAYSINH DATE,
    CCCD VARCHAR2(20),
    SONHA NVARCHAR2(50),
    TENDUONG NVARCHAR2(100),
    QUANHUYEN NVARCHAR2(50),
    TINHTP NVARCHAR2(50),
    TIENSUBENH NVARCHAR2(1000),
    TIENSUBENHGD NVARCHAR2(1000),
    DIUNGTHUOC NVARCHAR2(1000)
);

-- Bảng THÔNG BÁO (Độc lập, dùng cho OLS)
CREATE TABLE THONG_BAO (
    MATB VARCHAR2(20) PRIMARY KEY,
    NOIDUNG NVARCHAR2(1000),
    NGAYGIO TIMESTAMP,
    DIADIEM NVARCHAR2(100),
    OLS_LABEL NUMBER(10) -- Cột lưu mã số của nhãn OLS
);


-- ==========================================
-- 2. TẠO CÁC BẢNG PHỤ THUỘC (Có khóa ngoại)
-- ==========================================

-- Bảng HỒ SƠ BỆNH ÁN (HSBA)
CREATE TABLE HSBA (
    MAHSBA VARCHAR2(20) PRIMARY KEY,
    MABN VARCHAR2(20),
    NGAY DATE,
    CHANDOAN NVARCHAR2(500),
    DIEUTRI NVARCHAR2(500),
    MABS VARCHAR2(20),
    MAKHOA VARCHAR2(20),
    KETLUAN NVARCHAR2(500),
    
    -- Ràng buộc khóa ngoại
    CONSTRAINT FK_HSBA_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    CONSTRAINT FK_HSBA_NHANVIEN FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HSBA_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

-- Bảng DỊCH VỤ HỒ SƠ BỆNH ÁN (HSBA_DV)
CREATE TABLE HSBA_DV (
    MAHSBA VARCHAR2(20),
    LOAIDV NVARCHAR2(100),
    NGAYDV DATE,
    MAKTV VARCHAR2(20),
    KETQUA NVARCHAR2(500),
    
    -- Khóa chính kết hợp
    PRIMARY KEY (MAHSBA, LOAIDV, NGAYDV),
    
    -- Ràng buộc khóa ngoại
    CONSTRAINT FK_HSBADV_HSBA FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA),
    CONSTRAINT FK_HSBADV_NHANVIEN FOREIGN KEY (MAKTV) REFERENCES NHANVIEN(MANV)
);

-- Bảng ĐƠN THUỐC
CREATE TABLE DONTHUOC (
    MAHSBA VARCHAR2(20),
    TENTHUOC NVARCHAR2(100),
    NGAYDT DATE,
    LIEUDUNG NVARCHAR2(200),
    
    -- Khóa chính kết hợp
    PRIMARY KEY (MAHSBA, TENTHUOC, NGAYDT),
    
    -- Ràng buộc khóa ngoại
    CONSTRAINT FK_DONTHUOC_HSBA FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA)
);

