-- ================================================================
-- TASK 5 - STANDARD AUDIT
-- Chay sau khi da chay oracle/CQ2026-CQ16-PH1-Database.sql.
--
-- Muc tieu:
--   1. Cai dat Standard Audit ro rang cho Task 5.
--   2. Audit cac hanh vi tren table/view/procedure cu the.
--   3. Tao view rieng V_TASK5_STANDARD_AUDIT_LOG de demo SQL/Oracle.
--   4. UI van doc duoc qua V_ALL_AUDIT_LOG voi filter LOAI_AUDIT = STANDARD.
--
-- Nen chay bang SYS AS SYSDBA hoac SYSTEM co quyen DBA.
-- Neu audit_trail moi duoc doi sang DB, EXTENDED thi can restart database.
-- ================================================================

SET SERVEROUTPUT ON
SET LINES 180 PAGES 100

PROMPT == TASK 5 STANDARD AUDIT: CHECK AUDIT_TRAIL ==
SHOW PARAMETER audit_trail;

PROMPT == TASK 5 STANDARD AUDIT: ENABLE DB EXTENDED AUDIT IF NEEDED ==
-- Neu audit_trail dang NONE, lenh nay bat audit vao DB voi SQL_TEXT day du.
-- Can restart database neu gia tri vua duoc thay doi.
ALTER SYSTEM SET audit_trail = DB, EXTENDED SCOPE = SPFILE;

PROMPT == TASK 5 STANDARD AUDIT: GRANT AUDIT TRAIL READ PRIVILEGES ==
GRANT SELECT ON SYS.DBA_AUDIT_TRAIL TO ADMIN_PHANHE1;
GRANT SELECT ON SYS.DBA_OBJ_AUDIT_OPTS TO ADMIN_PHANHE1;
GRANT SELECT ON SYS.DBA_STMT_AUDIT_OPTS TO ADMIN_PHANHE1;
GRANT SELECT ON SYS.DBA_PRIV_AUDIT_OPTS TO ADMIN_PHANHE1;

PROMPT == TASK 5 STANDARD AUDIT: CREATE STANDARD AUDIT VIEW ==
CREATE OR REPLACE VIEW ADMIN_PHANHE1.V_TASK5_STANDARD_AUDIT_LOG AS
SELECT
    USERNAME AS NGUOI_DUNG,
    TO_CHAR(EXTENDED_TIMESTAMP, 'YYYY/MM/DD HH24:MI:SS') AS THOI_GIAN,
    ACTION_NAME AS HANH_DONG,
    OWNER || '.' || OBJ_NAME AS DOI_TUONG,
    CAST(SQL_TEXT AS VARCHAR2(2000)) AS CAU_LENH_SQL,
    CASE RETURNCODE
        WHEN 0 THEN 'Thanh cong'
        ELSE 'That bai (Ma loi: ' || RETURNCODE || ')'
    END AS TRANG_THAI,
    USERHOST AS MAY_TRAM,
    TERMINAL AS TERMINAL
FROM SYS.DBA_AUDIT_TRAIL
WHERE USERNAME NOT IN ('SYS', 'SYSTEM', 'DBSNMP', 'SYSMAN')
ORDER BY EXTENDED_TIMESTAMP DESC;

PROMPT == TASK 5 STANDARD AUDIT: CLEAN OLD STANDARD AUDIT OPTIONS ==
NOAUDIT SESSION;
NOAUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.HSBA;
NOAUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.HSBA_DV;
NOAUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.DONTHUOC;
NOAUDIT SELECT ON ADMIN_PHANHE1.V_ALL_AUDIT_LOG;
NOAUDIT SELECT ON ADMIN_PHANHE1.V_TASK5_STANDARD_AUDIT_LOG;
NOAUDIT EXECUTE ON ADMIN_PHANHE1.SP_BACKUP_DATAPUMP;
NOAUDIT EXECUTE ON ADMIN_PHANHE1.SP_RESTORE_DATAPUMP;
NOAUDIT EXECUTE ON ADMIN_PHANHE1.SP_RESTORE_FLASHBACK;
NOAUDIT TABLE;

PROMPT == TASK 5 STANDARD AUDIT: INSTALL STANDARD AUDIT CONTEXTS ==

-- Ngu canh 1: Dang nhap that bai.
-- Dung de phat hien brute-force/do mat khau.
AUDIT SESSION WHENEVER NOT SUCCESSFUL;

-- Ngu canh 2: Table audit tren HSBA.
-- Ghi nhan SELECT/INSERT/UPDATE/DELETE thanh cong va that bai.
AUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.HSBA BY ACCESS WHENEVER SUCCESSFUL;
AUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.HSBA BY ACCESS WHENEVER NOT SUCCESSFUL;

-- Ngu canh 3: Table audit tren HSBA_DV.
-- Bang nay lien quan dich vu chan doan cua KTV.
AUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.HSBA_DV BY ACCESS WHENEVER SUCCESSFUL;
AUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.HSBA_DV BY ACCESS WHENEVER NOT SUCCESSFUL;

-- Ngu canh 4: Table audit tren DONTHUOC.
-- Bang nay co du lieu don thuoc, can ghi nhan truy cap/chinh sua.
AUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.DONTHUOC BY ACCESS WHENEVER SUCCESSFUL;
AUDIT SELECT, INSERT, UPDATE, DELETE ON ADMIN_PHANHE1.DONTHUOC BY ACCESS WHENEVER NOT SUCCESSFUL;

-- Ngu canh 5: View audit log bi doc.
-- Chinh thao tac xem log cung duoc ghi vet.
AUDIT SELECT ON ADMIN_PHANHE1.V_ALL_AUDIT_LOG BY ACCESS;
AUDIT SELECT ON ADMIN_PHANHE1.V_TASK5_STANDARD_AUDIT_LOG BY ACCESS;

-- Ngu canh 6: Procedure backup/recover rui ro cao.
AUDIT EXECUTE ON ADMIN_PHANHE1.SP_BACKUP_DATAPUMP BY ACCESS;
AUDIT EXECUTE ON ADMIN_PHANHE1.SP_RESTORE_DATAPUMP BY ACCESS;
AUDIT EXECUTE ON ADMIN_PHANHE1.SP_RESTORE_FLASHBACK BY ACCESS;

-- Ngu canh 7: DDL tren table trong schema.
AUDIT TABLE BY ACCESS;

PROMPT == TASK 5 STANDARD AUDIT: VERIFY OBJECT AUDIT OPTIONS ==
SELECT owner, object_name, object_type,
       sel, ins, upd, del, exe
FROM dba_obj_audit_opts
WHERE owner = 'ADMIN_PHANHE1'
  AND object_name IN (
      'HSBA',
      'HSBA_DV',
      'DONTHUOC',
      'V_ALL_AUDIT_LOG',
      'V_TASK5_STANDARD_AUDIT_LOG',
      'SP_BACKUP_DATAPUMP',
      'SP_RESTORE_DATAPUMP',
      'SP_RESTORE_FLASHBACK'
  )
ORDER BY object_type, object_name;

PROMPT == TASK 5 STANDARD AUDIT: VERIFY STATEMENT AUDIT OPTIONS ==
SELECT audit_option, success, failure
FROM dba_stmt_audit_opts
WHERE audit_option IN ('CREATE TABLE', 'DROP TABLE', 'ALTER TABLE', 'TABLE', 'SESSION')
ORDER BY audit_option;

PROMPT == DONE TASK 5 STANDARD AUDIT SETUP ==
