-- ================================================================
-- TEST TASK 1 - RBAC CHO KY THUAT VIEN VA BENH NHAN
-- Chay sau khi da chay oracle/CQ2026-CQ16-PH1-Database.sql.
-- Lenh goi goi y:
--   sqlplus /nolog @oracle/test_task1_rbac.sql
--
-- Script nay tao tam user/dong du lieu KTV NV7777 de test, sau do tu cleanup.
-- Benh nhan mau duoc lay tu dong tu bang BENHNHAN va password user benh nhan
-- mau se duoc reset ve 123456 de test dang nhap.
-- ================================================================

SET SERVEROUTPUT ON
SET LINES 180 PAGES 100 VERIFY OFF

WHENEVER SQLERROR EXIT SQL.SQLCODE

CONNECT ADMIN_PHANHE1/"Admin@123456"@//127.0.0.1:1521/orcl21

PROMPT == ADMIN: kiem tra object RBAC ==
SELECT object_name, object_type, status
FROM user_objects
WHERE object_name IN (
    'V_RBAC_KTV_THONGTIN',
    'V_RBAC_KTV_DICHVU',
    'V_RBAC_BENHNHAN_THONGTIN',
    'SP_SYNC_TASK1_RBAC_USERS'
)
ORDER BY object_type, object_name;

SELECT role
FROM dba_roles
WHERE role IN ('ROLE_KYTHUATVIEN', 'ROLE_BENHNHAN')
ORDER BY role;

SELECT owner, table_name, privilege, grantee
FROM dba_tab_privs
WHERE owner = 'ADMIN_PHANHE1'
  AND grantee IN ('ROLE_KYTHUATVIEN', 'ROLE_BENHNHAN')
  AND table_name LIKE 'V_RBAC_%'
ORDER BY grantee, table_name, privilege;

SELECT owner, table_name, column_name, privilege, grantee
FROM dba_col_privs
WHERE owner = 'ADMIN_PHANHE1'
  AND grantee IN ('ROLE_KYTHUATVIEN', 'ROLE_BENHNHAN')
  AND table_name LIKE 'V_RBAC_%'
ORDER BY grantee, table_name, column_name;

COLUMN SAMPLE_BN NEW_VALUE SAMPLE_BN NOPRINT
SELECT MIN(MABN) AS SAMPLE_BN
FROM ADMIN_PHANHE1.BENHNHAN;

BEGIN
    IF '&SAMPLE_BN' IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Can co it nhat 1 dong BENHNHAN de test BN RBAC.');
    END IF;
END;
/

PROMPT == ADMIN: tao du lieu KTV test tam ==
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

BEGIN
    DELETE FROM ADMIN_PHANHE1.HSBA_DV WHERE MAHSBA = 'HSTASK1' OR MAKTV = 'NV7777';
    DELETE FROM ADMIN_PHANHE1.HSBA WHERE MAHSBA = 'HSTASK1';
    DELETE FROM ADMIN_PHANHE1.NHANVIEN WHERE MANV = 'NV7778';
    DELETE FROM ADMIN_PHANHE1.NHANVIEN WHERE MANV = 'NV7777';
    DELETE FROM ADMIN_PHANHE1.KHOA WHERE MAKHOA = 'KTEST';
    COMMIT;

    BEGIN
        EXECUTE IMMEDIATE 'DROP USER C##NV7777 CASCADE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1918 THEN RAISE; END IF;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP USER C##NV7778 CASCADE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1918 THEN RAISE; END IF;
    END;
END;
/

INSERT INTO ADMIN_PHANHE1.KHOA (MAKHOA, TENKHOA)
VALUES ('KTEST', N'Khoa test RBAC');

INSERT INTO ADMIN_PHANHE1.NHANVIEN
    (MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, VAITRO, CHUYENKHOA, COSO)
VALUES
    ('NV7777', N'KTV Task1', N'Nam', DATE '1990-01-01', '099999999999',
     N'Test', '0900000000', N'Ky thuat vien', N'Xet nghiem', N'CS Task1');

INSERT INTO ADMIN_PHANHE1.NHANVIEN
    (MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, VAITRO, CHUYENKHOA, COSO)
VALUES
    ('NV7778', N'Nhan vien stale role', N'Nam', DATE '1990-01-01', '088888888888',
     N'Test', '0900000001', N'Nhan vien khac', N'Khac', N'CS Task1');

INSERT INTO ADMIN_PHANHE1.HSBA
    (MAHSBA, MABN, NGAY, CHANDOAN, DIEUTRI, MABS, MAKHOA, KETLUAN)
VALUES
    ('HSTASK1', '&SAMPLE_BN', DATE '2026-06-20', N'Test RBAC',
     N'Test RBAC', NULL, 'KTEST', N'Test RBAC');

INSERT INTO ADMIN_PHANHE1.HSBA_DV
    (MAHSBA, LOAIDV, NGAYDV, MAKTV, KETQUA)
VALUES
    ('HSTASK1', N'Xet nghiem Task1', TIMESTAMP '2026-06-20 09:00:00',
     'NV7777', N'Chua co');

INSERT INTO ADMIN_PHANHE1.HSBA_DV
    (MAHSBA, LOAIDV, NGAYDV, MAKTV, KETQUA)
VALUES
    ('HSTASK1', N'Dich vu khong giao cho KTV', TIMESTAMP '2026-06-20 10:00:00',
     NULL, N'Khong duoc thay');

COMMIT;

CREATE USER C##NV7778 IDENTIFIED BY "123456";
GRANT CREATE SESSION TO C##NV7778;
GRANT ROLE_KYTHUATVIEN TO C##NV7778;

BEGIN
    ADMIN_PHANHE1.SP_SYNC_TASK1_RBAC_USERS('123456');
END;
/

ALTER USER C##NV7777 IDENTIFIED BY "123456" ACCOUNT UNLOCK;
ALTER USER C##&SAMPLE_BN IDENTIFIED BY "123456" ACCOUNT UNLOCK;

SELECT username, account_status
FROM dba_users
WHERE username IN ('C##NV7777', 'C##&SAMPLE_BN')
ORDER BY username;

SELECT grantee, granted_role
FROM dba_role_privs
WHERE grantee IN ('C##NV7777', 'C##&SAMPLE_BN')
  AND granted_role IN ('ROLE_KYTHUATVIEN', 'ROLE_BENHNHAN')
ORDER BY grantee, granted_role;

DECLARE
    v_stale_role_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_stale_role_count
    FROM dba_role_privs
    WHERE grantee = 'C##NV7778'
      AND granted_role = 'ROLE_KYTHUATVIEN';

    IF v_stale_role_count <> 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'SP_SYNC_TASK1_RBAC_USERS chua revoke ROLE_KYTHUATVIEN cua nhan vien khong phai KTV.');
    END IF;
END;
/

SELECT COUNT(*) AS ADMIN_HSBA_DV_TEST_ROWS
FROM ADMIN_PHANHE1.HSBA_DV
WHERE MAHSBA = 'HSTASK1';

WHENEVER SQLERROR CONTINUE

PROMPT == KTV: user C##NV7777 chi thay viec cua minh va chi sua cot duoc phep ==
CONNECT C##NV7777/"123456"@//127.0.0.1:1521/orcl21

SELECT USER AS LOGGED_USER FROM dual;
SELECT role FROM session_roles WHERE role = 'ROLE_KYTHUATVIEN';
SELECT COUNT(*) AS OWN_PROFILE_ROWS FROM ADMIN_PHANHE1.V_RBAC_KTV_THONGTIN;
SELECT MANV, HOTEN, VAITRO, SODT, COSO FROM ADMIN_PHANHE1.V_RBAC_KTV_THONGTIN;
SELECT COUNT(*) AS OWN_SERVICE_ROWS FROM ADMIN_PHANHE1.V_RBAC_KTV_DICHVU;
SELECT MAHSBA, LOAIDV, MAKTV, KETQUA
FROM ADMIN_PHANHE1.V_RBAC_KTV_DICHVU
ORDER BY LOAIDV;

UPDATE ADMIN_PHANHE1.V_RBAC_KTV_DICHVU
SET KETQUA = N'TASK1_KTV_OK'
WHERE MAHSBA = 'HSTASK1' AND MAKTV = 'NV7777';

UPDATE ADMIN_PHANHE1.V_RBAC_KTV_THONGTIN
SET SODT = '0911111111';

ROLLBACK;

PROMPT == KTV: cac lenh sau phai bi chan ==
UPDATE ADMIN_PHANHE1.V_RBAC_KTV_DICHVU
SET MAKTV = 'NV0003'
WHERE MAHSBA = 'HSTASK1';

SELECT COUNT(*) FROM ADMIN_PHANHE1.HSBA_DV;

PROMPT == BN: user C##&SAMPLE_BN chi thay ho so cua minh va chi sua cot duoc phep ==
CONNECT C##&SAMPLE_BN/"123456"@//127.0.0.1:1521/orcl21

SELECT USER AS LOGGED_USER FROM dual;
SELECT role FROM session_roles WHERE role = 'ROLE_BENHNHAN';
SELECT COUNT(*) AS OWN_PATIENT_ROWS FROM ADMIN_PHANHE1.V_RBAC_BENHNHAN_THONGTIN;
SELECT MABN, TENBN, SONHA, TENDUONG, TIENSUBENH, DIUNGTHUOC
FROM ADMIN_PHANHE1.V_RBAC_BENHNHAN_THONGTIN;

UPDATE ADMIN_PHANHE1.V_RBAC_BENHNHAN_THONGTIN
SET SONHA = N'999',
    TENDUONG = N'Duong test RBAC',
    TIENSUBENH = N'Test RBAC cap nhat tien su benh';

ROLLBACK;

PROMPT == BN: cac lenh sau phai bi chan ==
UPDATE ADMIN_PHANHE1.V_RBAC_BENHNHAN_THONGTIN
SET TENBN = N'Ten bi chan';

SELECT COUNT(*) FROM ADMIN_PHANHE1.BENHNHAN;

PROMPT == ADMIN: cleanup du lieu KTV test tam ==
WHENEVER SQLERROR EXIT SQL.SQLCODE
CONNECT ADMIN_PHANHE1/"Admin@123456"@//127.0.0.1:1521/orcl21
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

BEGIN
    DELETE FROM ADMIN_PHANHE1.HSBA_DV WHERE MAHSBA = 'HSTASK1' OR MAKTV = 'NV7777';
    DELETE FROM ADMIN_PHANHE1.HSBA WHERE MAHSBA = 'HSTASK1';
    DELETE FROM ADMIN_PHANHE1.NHANVIEN WHERE MANV = 'NV7778';
    DELETE FROM ADMIN_PHANHE1.NHANVIEN WHERE MANV = 'NV7777';
    DELETE FROM ADMIN_PHANHE1.KHOA WHERE MAKHOA = 'KTEST';
    COMMIT;

    BEGIN
        EXECUTE IMMEDIATE 'DROP USER C##NV7777 CASCADE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1918 THEN RAISE; END IF;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP USER C##NV7778 CASCADE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1918 THEN RAISE; END IF;
    END;
END;
/

SELECT COUNT(*) AS REMAINING_TEST_ROWS
FROM ADMIN_PHANHE1.HSBA_DV
WHERE MAHSBA = 'HSTASK1' OR MAKTV = 'NV7777';

SELECT COUNT(*) AS REMAINING_TEST_USER
FROM dba_users
WHERE username IN ('C##NV7777', 'C##NV7778');

PROMPT == DONE TASK 1 RBAC TEST ==
EXIT
